### ISSUE TITLE
query('query') with .where() error on SSR

### ISSUE THREAD

**Issue by joelAppslabs** [hamedbaatour/angularfire-lite#18]
Hello, when doing query type 'query' with 'where' in firestore service, in the browser they work perfectly, but when testing it with ssr, it returns an error 400...

```
this.firestore.query('articles').where('slug', '==', 'article-2').on().subscribe(...)

```

**Comment by RakWojciech** [comment]
Can you share your repo ?

**Comment by hamedbaatour** [comment]
@JoelRicharte will investigate the issue
