### ISSUE TITLE
Error in firestore typings

### ISSUE THREAD

**Issue by TimGeerts** [hamedbaatour/angularfire-lite#20]
Hey, was using angularfire2 library but decided to give this library a try (cause of the simplicity).
However, when I try to build my application, I get a compilation error:  
`ERROR in node_modules/angularfire-lite/firestore/firestore.service.d.ts(33,39): error TS2503: Cannot find namespace 'firebase'.`

As I'm not that good with angular stuff yet, so I don't know if I can fix this myself, but I don't think so.

**Comment by hamedbaatour** [comment]
@TimGeerts just released a new version. upgrade to the new release (v5.2.0)

**Comment by hamedbaatour** [comment]
@TimGeerts if you still face any issues please report them and feel free to reopen this issue.
