### ISSUE TITLE
feat(angular): make angularfire-lite compatible with angular 6

### ISSUE THREAD

**Issue by cm45t3r** [hamedbaatour/angularfire-lite#22]
## Submission
- [ ] Regression 
- [ ] Bug report 
- [x] Feature request
- [ ] Documentation issue or request

## Description
Since the major release of Angular 6, it would be great to have AngularFire Lite fully compliant with the new version of Angular.

## Use case
Preserve AngularFire Lite great features while allowing developers to migrate their applications to Angular 6.

**Comment by hamedbaatour** [comment]
it's a work in progress check out this PR: #26
