### ISSUE TITLE
Property 'download' does not exist on type 'AngularFireLiteStorage'

### ISSUE THREAD

**Issue by anshap1719** [hamedbaatour/angularfire-lite#33]
After updating my project to Angular 7, while running `ng serve`, it shows the error mentioned in the title. On Angular 6, this wasn't happening. I know that Angular 7 was just released but I was wondering if there's a workaround for the time being until the project is updated.

**Comment by hamedbaatour** [comment]
use getDownloadURL(ref: string) instead
