### ISSUE TITLE
Collaboration with official AngularFire

### ISSUE THREAD

**Issue by davideast** [hamedbaatour/angularfire-lite#6]
Hey @hamedbaatour!

I really love the initiative you took here, but I'd prefer not to fragment the ecosystem. We have a lot of great things planned for AngularFire and I'd love to include you in on them rather than having a separate library that does the same thing.

What do you say?

**Comment by hamedbaatour** [comment]
@davideast  Thank you for your kind words. What I would like to do with AngularFire Lite is to enrich the ecosystem and not to fragment it. Can you please elaborate more on how AngularFire Lite could collaborate with Angularfire2?

**Comment by davideast** [comment]
AngularFire will land SSR, Messaging, and Storage support soon. At that point these libraries will do the same thing with different APIs. Instead of having two libraries I'd love if we could collaborate on one single library, that being the official AngularFire library.

There's plenty of awesome things to accomplish and I think we could do great stuff if we worked together rather than separately.

**Comment by MarkPieszak** [comment]
It’d definitely be ideal to just merge your awesome work here into the main repo 👍
@hamedbaatour

**Comment by AnthonyNahas** [comment]
@hamedbaatour for which reason should someone reject this offer ?

**Comment by rubenheymans** [comment]
@davideast any updates on this, can we use SSR with angularfire2?
