### ISSUE TITLE
Supporting transactions for Firestore

### ISSUE THREAD

**Issue by trakhimenok** [hamedbaatour/angularfire-lite#8]
Is there a plan / roadmap for supporting transactions by AngularFire Light for Firestore?

I see here is a TODO but wonder if it can be expected to lend in nearest time.

https://github.com/hamedbaatour/angularfire-lite/blob/cf25ce2e8b4fc7fd1fdfc78cbbfc1aea850750e3/angularfire-lite/src/firestore/firestore.service.ts#L35

**Comment by hamedbaatour** [comment]
@astec yes definitely! it is on my calendar and will update this issue once it's done. Thank you for opening this issue and if you have any further features requests or suggestions please do not hesitate to open an issue in the repo and will be more than happy to work on it.

**Comment by trakhimenok** [comment]
Thanks for putting `important` label as lack of transactions support is a `no-go` for me and I guess for most real life applications.

I wonder if I can just call `runTransaction()` on some db reference object in meantime. Or `read/write` methods should be modified as well?

**Comment by hamedbaatour** [comment]
@astec currently read and write methods preform the basic read and write operations the rationale behind this is to keep AngularFire Lite API simple and close to the native Firebase API so probably another separate method will land on the next release  `runTransaction()` .

**Comment by hamedbaatour** [comment]
@astec 

🎉 **AngularFire Lite v5.1 Release:**

- Observable based Transactions and Batched Writes 😮 
- Firestore realtime Queries with SSR support
- Better RD Querying 

more to come in the next release including:

- Storage and Transactions SSR support
- Firestore and RD offline capabilities 
- FCM fixes

a ton of features and it is **50% lighter than Angularfire2** 😀 

but I have a lot of work to do on the documentation side.
for now, you can check the updated demo for a simple implementation example [here](https://github.com/hamedbaatour/angularfire-lite-demo)
